CREATE DATABASE todo_backend DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

USE todo_backend;
DROP TABLE IF EXISTS `tasks`;
CREATE TABLE `tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT now(),
  `editedAt` DATETIME NULL DEFAULT NULL,
  `targetDate` DATETIME NULL DEFAULT NULL,
  `finishDate` DATETIME NULL DEFAULT NULL,
  `clear` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci;